@startuml ContextDiagram
left to right direction
skinparam packagestyle rect

' Actors
actor "Warehouse Manager" as WarehouseManager
actor "Retailer Manager" as RetailerManager
actor "Quality Office" as QualityOffice
actor "Warehouse Worker" as WarehouseWorker
actor Administrator
actor "Transportation Service" as TransportationService
actor "Payment Service" as PayementService
actor "Cloud Service" as CloudService

' Associations
WarehouseManager --|> WarehouseWorker
rectangle System{
	(EZWH) -- QualityOffice
	(EZWH) -- TransportationService
	(EZWH) -- PayementService
	(EZWH) -- CloudService
	(EZWH) -- WarehouseWorker
	(EZWH) -- RetailerManager
	(EZWH) -- WarehouseWorker
	(EZWH) -- Administrator

}
@enduml